---
abstract: 'Base module for generating SVG graphics'
author:
  - 'Leo Lapworth <LLAP@cuckoo.org>'
build_requires:
  ExtUtils::MakeMaker: '6.59'
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: '6.59'
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.12'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: SVG-TT-Graph
no_index:
  directory:
    - inc
    - t
recommends:
  Compress::Zlib: 0
  XML::Tidy: 0
requires:
  DateTime: '0.1'
  HTTP::Date: '0.1'
  Template: '2.08'
  perl: 5.6.1
resources:
  bugtracker: https://github.com/ranguard/svg-tt-graph/issues
  license: http://dev.perl.org/licenses/
  repository: git://github.com/ranguard/svg-tt-graph.git
version: '0.24'
