# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SVG-TT-Graph
version:      0.09
version_from: lib/SVG/TT/Graph.pm
installdirs:  site
requires:
    DateTime:                      0.1
    HTTP::Date:                    0.1
    Template:                      2.08

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
