#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SVG-TT-Graph
version:      0.07
version_from: lib/SVG/TT/Graph.pm
installdirs:  site
requires:
    Template:                      2.08
    HTTP::Date:                    0.1
    DateTime:                      0.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
